apiVersion: v1
kind: Service
metadata:
  name: tomcat-demo
  labels:
    app: tomcat-demo
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: tomcat-demo
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-demo-deployment
  labels:
    app: tomcat-demo
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: tomcat-demo
  template:
    metadata:
      labels:
        app: tomcat-demo
    spec:
      containers:
      - image: adithya321/jenkins-tomcat-demo:latest
        name: tomcat-demo
        ports:
        - containerPort: 8080
          name: tomcat-demo
        readinessProbe:
          httpGet:
             path: /
             port: 8080